var _pictures=[["woman.jpg",640,426],["blue_rose.jpg",640,400],["bamboo.jpg",640,480],["crayons.jpg",600,480],["hawaii.jpg",640,480],["swan.jpg",660,468]],_image_path,_image_width,_image_height,_num_rows,_num_cols,_tile_width,_tile_height,_gap_size=2,_empty_tile,_container,_frame,_just_moved,_able_to_click,_tiles=[],_divs=[];function colToLeft(b){return b*_tile_width}function rowToTop(b){return b*_tile_height}function rowGap(b){return b*_gap_size}function colGap(b){return b*_gap_size}
function createDiv(b,c){var a=document.createElement("div");a.row=b;a.col=c;a.style.width=_tile_width+"px";a.style.height=_tile_height+"px";a.style.left=colGap(c)+colToLeft(c)+"px";a.style.top=rowGap(b)+rowToTop(b)+"px";a.className="tile";a.style.backgroundImage="url("+_image_path+")";a.style.backgroundPosition=""+-colToLeft(c)+"px "+-rowToTop(b)+"px";a.style.backgroundRepeat="no-repeat";a.onclick=tileClicked;a.slide=function(b,c,d,e,f){a.row=d;a.col=e;var k=d-b,l=e-c,m=rowToTop(d)+rowGap(d),n=colToLeft(e)+
colGap(e),i=parseInt(a.style.left,10),j=parseInt(a.style.top,10);if(i!=n)a.style.left=Math.abs(n-i)>=f?i+l*f+"px":i+l+"px",setTimeout(function(){a.slide(b,c,d,e,f)},1);if(j!=m)a.style.top=Math.abs(m-j)>=f?j+k*f+"px":j+k+"px",setTimeout(function(){a.slide(b,c,d,e,f)},1)};return a}function createTiles(b,c){for(var a=0;a<_num_rows;a++)for(var g=0;g<_num_cols;g++)if(a==b&&g==c)_tiles.push(_empty_tile);else{var h=new Tile(a,g);_tiles.push(h);h=createDiv(a,g);_divs.push(h);_container.appendChild(h)}}
function tileClicked(b){if(_able_to_click)b=b.target,getTile(b.row,b.col).slide(5)}function getTile(b,c){for(var a=0;a<_tiles.length;a++)if(_tiles[a].row==b&&_tiles[a].col==c)return _tiles[a]}function getDiv(b,c){for(var a=0;a<_divs.length;a++)if(_divs[a].row==b&&_divs[a].col==c)return _divs[a]}
function generateRandomPuzzle(){_tile_width=Math.floor(_image_width/_num_cols);_tile_height=Math.floor(_image_height/_num_rows);var b,c;Math.random()<0.5?b=0:b=_num_rows-1;Math.random()<0.5?c=0:c=_num_cols-1;_just_moved=_empty_tile=new Tile(b,c);createTiles(_empty_tile.row,_empty_tile.col);_able_to_click=!1;shuffleTiles(_num_cols*_num_rows*3)}
function shuffleTiles(b){if(b>0){for(var c=_empty_tile.neighbors(),a=[Math.floor(Math.random()*c.length)],a=c[a];a.row==_just_moved.row&&a.col==_just_moved.col;)a=[Math.floor(Math.random()*c.length)],a=c[a];c=getTile(a.row,a.col);c.slide(50);_just_moved=c;setTimeout(function(){shuffleTiles(b-1)},200)}else _able_to_click=!0}
window.onload=function(){_container=document.getElementById("tile_container");_frame=document.getElementById("puzzle_frame");var b=_pictures[Math.floor(Math.random()*_pictures.length)];_num_rows=Math.floor(Math.random()*3)+2;_num_cols=Math.floor(Math.random()*3)+2;_image_path="puzzle_images/"+b[0];_image_width=b[1];_image_height=b[2];_frame.style.width=_image_width+colGap(_num_cols)+"px";_frame.style.height=_image_height+rowGap(_num_rows)+"px";_container.style.width=_image_width+"px";_container.style.height=
_image_height+"px";generateRandomPuzzle()};
function Tile(b,c){this.row=b;this.col=c;this.valid=function(){var a=this.col>=0&&this.col<_num_cols;return this.row>=0&&this.row<_num_rows&&a};this.neighbors=function(){var a=[],b=new Tile(this.row,this.col-1),c=new Tile(this.row,this.col+1),d=new Tile(this.row-1,this.col),e=new Tile(this.row+1,this.col);b.valid()&&a.push(b);c.valid()&&a.push(c);d.valid()&&a.push(d);e.valid()&&a.push(e);return a};this.slide=function(a){for(var b=this.neighbors(),c=b.length;c--;)if(b[c].row==_empty_tile.row&&b[c].col==
_empty_tile.col){var b=this.row,c=this.col,d=_empty_tile.row,e=_empty_tile.col;this.row=d;this.col=e;_empty_tile.row=b;_empty_tile.col=c;getDiv(b,c).slide(b,c,d,e,a);break}}};