var _pictures=[["woman.jpg",640,426],["blue_rose.jpg",640,400],["bamboo.jpg",640,480],["crayons.jpg",600,480],["hawaii.jpg",640,480],["swan.jpg",660,468]],_image_path,_image_width,_image_height,_num_rows,_num_cols,_tile_width,_tile_height,_gap_size=2,_empty_tile,_container,_frame,_just_moved,_able_to_click,_tiles=[],_divs=[];function colToLeft(a){return a*_tile_width}function rowToTop(a){return a*_tile_height}function rowGap(a){return a*_gap_size}function colGap(a){return a*_gap_size}
function createDiv(a,c){var b=document.createElement("div");b.row=a;b.col=c;b.style.width=_tile_width+"px";b.style.height=_tile_height+"px";b.style.left=colGap(c)+colToLeft(c)+"px";b.style.top=rowGap(a)+rowToTop(a)+"px";b.className="tile";b.style.backgroundImage="url("+_image_path+")";b.style.backgroundPosition=""+-colToLeft(c)+"px "+-rowToTop(a)+"px";b.onclick=tileClicked;b.slide=function(a,c,d,e,f){b.row=d;b.col=e;var i=d-a,j=e-c,k=rowToTop(d)+rowGap(d),l=colToLeft(e)+colGap(e),g=parseInt(b.style.left,
10),h=parseInt(b.style.top,10);if(g!=l)b.style.left=Math.abs(l-g)>=f?g+j*f+"px":g+j+"px",setTimeout(function(){b.slide(a,c,d,e,f)},1);if(h!=k)b.style.top=Math.abs(k-h)>=f?h+i*f+"px":h+i+"px",setTimeout(function(){b.slide(a,c,d,e,f)},1)};return b}function createTiles(){for(var a=0;a<_num_rows;a++)for(var c=0;c<_num_cols;c++)if(a==_empty_tile.row&&c==_empty_tile.col)_tiles.push(_empty_tile);else{_tiles.push(new Tile(a,c));var b=createDiv(a,c);_divs.push(b);_container.appendChild(b)}}
function tileClicked(a){if(_able_to_click)a=a.target,getTile(a.row,a.col).slide(5)}function getTile(a,c){for(var b=0;b<_tiles.length;b++)if(_tiles[b].row==a&&_tiles[b].col==c)return _tiles[b]}function getDiv(a,c){for(var b=0;b<_divs.length;b++)if(_divs[b].row==a&&_divs[b].col==c)return _divs[b]}
function generateRandomPuzzle(){_tile_width=Math.floor(_image_width/_num_cols);_tile_height=Math.floor(_image_height/_num_rows);var a,c;Math.random()<0.5?a=0:a=_num_rows-1;Math.random()<0.5?c=0:c=_num_cols-1;_just_moved=_empty_tile=new Tile(a,c);createTiles();_able_to_click=!1;shuffleTiles(_num_cols*_num_rows*3)}
function shuffleTiles(a){if(a>0){for(var c=_empty_tile.neighbors(),b=[Math.floor(Math.random()*c.length)],b=c[b];b.row==_just_moved.row&&b.col==_just_moved.col;)b=[Math.floor(Math.random()*c.length)],b=c[b];c=getTile(b.row,b.col);c.slide(50);_just_moved=c;setTimeout(function(){shuffleTiles(a-1)},250)}else _able_to_click=!0}
window.onload=function(){_container=document.getElementById("tile_container");_frame=document.getElementById("puzzle_frame");var a=_pictures[Math.floor(Math.random()*_pictures.length)];_image_path="puzzle_images/"+a[0];_image_width=a[1];_image_height=a[2];_num_rows=Math.floor(Math.random()*3)+2;_num_cols=Math.floor(Math.random()*3)+2;_frame.style.width=_image_width+colGap(_num_cols)+"px";_frame.style.height=_image_height+rowGap(_num_rows)+"px";_container.style.width=_image_width+"px";_container.style.height=
_image_height+"px";generateRandomPuzzle()};
function Tile(a,c){this.row=a;this.col=c;this.valid=function(){var b=this.col>=0&&this.col<_num_cols;return this.row>=0&&this.row<_num_rows&&b};this.neighbors=function(){var b=[],a=new Tile(this.row,this.col-1),c=new Tile(this.row,this.col+1),d=new Tile(this.row-1,this.col),e=new Tile(this.row+1,this.col);a.valid()&&b.push(a);c.valid()&&b.push(c);d.valid()&&b.push(d);e.valid()&&b.push(e);return b};this.slide=function(b){for(var a=this.neighbors(),c=a.length;c--;)if(a[c].row==_empty_tile.row&&a[c].col==
_empty_tile.col){var a=this.row,c=this.col,d=_empty_tile.row,e=_empty_tile.col;this.row=d;this.col=e;_empty_tile.row=a;_empty_tile.col=c;getDiv(a,c).slide(a,c,d,e,b);break}}};